import fs from "node:fs";
import path from "node:path";
import { getLocalSchemas } from "../../core/workspace.js";
import { logger } from "../../core/logger.js";
import type { CollectionField } from "../../types/project.js";

function mapType(field: CollectionField, indent = "    "): string {
  switch (field.type) {
    case "String":
      return "string";
    case "Number":
      return "number";
    case "Boolean":
      return "boolean";
    case "Date":
      return "string | Date";
    case "Ref":
      return "string";
    case "Array":
      if (field.fields && field.fields.length > 0) {
        // We only support arrays of objects for now, or array of singular types if it's a single field with empty key
        if (field.fields.length === 1 && !field.fields[0].key) {
           return `Array<${mapType(field.fields[0], indent)}>`;
        }
        return `Array<${parseFields(field.fields, indent + "  ")}>`;
      }
      return "any[]";
    case "Object":
      if (field.fields && field.fields.length > 0) {
        return parseFields(field.fields, indent + "  ");
      }
      return "Record<string, any>";
    default:
      return "any";
  }
}

function parseFields(fields: CollectionField[], indent: string): string {
  let out = "{\n";
  for (const f of fields) {
    const isOptional = !f.required ? "?" : "";
    const typeStr = mapType(f, indent);
    out += `${indent}  "${f.key}"${isOptional}: ${typeStr};\n`;
  }
  out += `${indent}}`;
  return out;
}

export async function generateCommand(): Promise<void> {
  const schemas = getLocalSchemas();

  if (schemas.length === 0) {
    logger.error("No schemas found in .ub/schemas/. Run 'ub pull' first.");
    process.exitCode = 1;
    return;
  }

  let dtsContent = `// Auto-generated by urBackend CLI\n// Do not edit this file directly\n\n`;
  dtsContent += `export interface UrBackendTypes {\n`;

  for (const { name, schema } of schemas) {
    if (!schema.model || !Array.isArray(schema.model)) continue;
    
    dtsContent += `  "${name}": {\n`;
    dtsContent += `    _id: string;\n`;
    
    for (const field of schema.model as CollectionField[]) {
      const isOptional = !field.required ? "?" : "";
      const typeStr = mapType(field, "  ");
      dtsContent += `    "${field.key}"${isOptional}: ${typeStr};\n`;
    }
    
    dtsContent += `    createdAt: string | Date;\n`;
    dtsContent += `    updatedAt: string | Date;\n`;
    dtsContent += `  };\n`;
  }

  dtsContent += `}\n`;

  const outputPath = path.join(process.cwd(), "urbackend.d.ts");
  
  try {
    fs.writeFileSync(outputPath, dtsContent, "utf8");
    logger.success(`Generated TypeScript definitions at ./urbackend.d.ts`);
  } catch (error) {
    logger.error(`Failed to write urbackend.d.ts: ${(error as Error).message}`);
    process.exitCode = 1;
  }
}
